name: 'Swm github actions basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL_LEVEL'
jobs:
  build-test:
    name: 'build and test'
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"
  deploy-dev:
    name: 'deploy-dev'
    needs:
      - build-test
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"
  deploy-staging1:
    name: 'deploy staging1'
    needs:
      - deploy-dev
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"
  deploy-staging2:
    name: 'deploy staging2'
    needs:
      - deploy-dev
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"
  deploy-prod:
    name: 'deploy-prod'
    needs:
      - deploy-staging1
      - deploy-staging2
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"