name: 'Swm github actions basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL_LEVEL'
jobs:
  first-job:
    name: 'First job'

    runs-on: ubuntu-latest
    env:
      JOB_LEVEL_1: 'JOB LEVEL VALUE 1'
    steps:
    - name : say hello word 1
      id: helloworld1
      shell:  bash
      
      run: |
        echo 'hello world from  step1'
        randomValue="swm$(echo $RANDOM)"
        echo "::add-mask::$randomValue"
        echo "STEP_VALUE=$randomValue" >> $GITHUB_OUTPUT

    - name : say hello word 2
      shell:  pwsh
      run: |
        echo 'hello world from  step2'
        echo "STEP_VALUE: ${{ steps.helloworld1.outputs.STEP_VALUE }}"
        echo "API_KEY: ${{ secretes.API_KEY }}"
  