name: 'Swm github actions basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL_LEVEL'
jobs:
  build-test:
    name: 'build and test'
    runs-on: 'ubuntu-latest'

    steps:
    - name : send a msg to webex space
      shell:  bash
      run: |
        curl -X POST 'https://webexapis.com/v1/messages' \
        -H 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
        -H 'Content-type: application/json' \
        -d '{
          "roomId": " ${{ secrets.WEBEX_ROOM_ID }}",
          "text": "메세지입니다 - FROM GITHUB ACTION"
        }'
    - name: Post Message to Webex Room
        uses: chrivand/action-webex-js@main
        env:
          WEBEX_TOKEN: ${{ secrets.WEBEX_TOKEN }}
          WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOM_ID }}
          MARKDOWN_MESSAGE: "**Hello, world! You just ran an action from ${{ github.repository }}.**"