name: 'Swm github actions basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL_LEVEL'
jobs:
  first-job:
    name: 'First job'
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        nodejs: [ '16', '18' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name : say hello word 1 - ${{ matrix.os }}
  
      shell:  bash
      
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "nodejs version: ${{ matrix.nodejs }}"

    steps:
    - name : say hello word 2 - ${{ matrix.os }}
      if: matrix.os == 'windows-latest'
  
      shell:  bash
      
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "nodejs version: ${{ matrix.nodejs }}"