name: 'Swm github actions basic'

on: push

jobs:
  first-job:
    name: 'First job'

    runs-on: ubuntu-latest

    steps:
    - name : 'say hello word 1';
      shell:  bash
      run: |
        echo 'hello world from  step2'
    - name : 'say hello word 3';
      shell:  pwsh
      run: |
        echo 'hello world from  step2'
