name: 'Swm github actions basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL_LEVEL'
jobs:
  build-test:
    name: 'build and test'
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"
  deploy-dev:
    name: 'deploy-dev'
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"
  deploy-staging:
    name: 'deploy staging'
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"
  deploy-prod:
    name: 'deploy-prod'
    runs-on: 'ubuntu-latest'

    steps:
    - name : say hello word 1
      shell:  bash
      run: |
        echo "hello world"